export const FAQQuestionAndAnswer = [
    {
      id: 1,
      question: "How does URL shortening work?",
      answer:
        "URL shortening works by taking a long URL and creating a shorter, condensed version that redirects to the original URL. When a user clicks on the shortened link, they are redirected to the intended destination. ",
    },
    {
      id: 2,
      question: "Is it necessary to create an account to use the URL shortening service ?",
      answer:
        "No, it is not necessary to create an account to use the URL shortening service. Our URL shortening service offers both anonymous and registered user options, providing flexibility based on your preference and needs.",
    },
    {
      id: 3,
      question: "Are the shortened links permanent? Will they expire?",
      answer: "The shortened links generated by our URL shortening service are intended to be permanent and will not expire. Once you create a shortened link, it will remain functional and accessible as long as our service is active",
    },
    {
      id: 4,
      question: "Are there any limitations on the number of URLs I can shorten?",
      answer:
        "Our URL shortening service does not impose any limitations on the number of URLs you can shorten. You are welcome to shorten as many URLs as you need, without any restrictions.",
    },
    {
      id: 5,
      question: "Can I customize the shortened URLs to reflect my brand or content?",
      answer:
        "Absolutely! Our URL shortening service provides options for customizing the shortened URLs to reflect your brand or content. We understand the importance of maintaining consistency and enhancing brand recognition in your online presence",
    },
    {
      id: 6,
      question: "Can I track the performance of my shortened URLs? ",
      answer:
        "Absolutely! Our URL shortening service provides comprehensive tracking and analytics features that allow you to monitor and analyze the performance of your shortened URLs.",
    },
    {
      id: 7,
      question: "How secure is the URL shortening service? Are the shortened links protected against spam or malicious activity?",
      answer:
        "The security of our URL shortening service is of utmost importance to us. We have implemented measures to ensure the protection of shortened links against spam and malicious activity.",
    },
    {
      id: 8,
      question: "What is a QR code and what can it do?",
      answer:
        "A QR code, short for Quick Response code, is a two-dimensional barcode that contains encoded information. It is designed to be quickly scanned and decoded using a smartphone or QR code reader.",
    },
    {
      id: 9,
      question: "Is there an API available for integrating the URL shortening service into my own application or websites?",
      answer:
        "Yes, we provide an API that allows you to integrate our URL shortening service into your own applications or websites. Our API enables you to programmatically generate shortened URLs, retrieve analytics data, and perform other related operations.",
    },
  ];
  
  export default FAQQuestionAndAnswer;